namespace :db do
    desc "Export recipes to recipes_seed.rb"
    task export_recipes: :environment do
      seed_file = Rails.root.join('db', 'recipes_seed.rb')
  
      File.open(seed_file, 'w') do |file|
        file.puts "# This file was generated by db:export_recipes\n\n"
        Recipe.all.each do |recipe|
          file.puts "Recipe.create("
          file.puts "  name: '#{recipe.name}',"
          file.puts "  description: '#{recipe.description}',"
          file.puts "  origin: '#{recipe.origin}',"
          file.puts "  steps: '#{recipe.steps}',"
          file.puts "  photo: '#{recipe.photo}'"
          file.puts ")"
          file.puts "\n"
        end
      end
  
      puts "Recipes have been exported to db/recipes_seed.rb"
    end
  end
  