# This file was generated by db:export_recipes

Recipe.create(
  title: 'Scrambled Eggs',
  ingredients: 'Eggs, Butter, Salt, Pepper',
  instructions: '1. Whisk eggs. 2. Melt butter in a pan. 3. Pour eggs into pan. 4. Stir gently until fully cooked.',
  cooking_time: '10',
  servings: 2,
  difficulty: 'Easy'
)

Recipe.create(
  title: 'Cajun Chicken',
  ingredients: 'Chicken Breasts, Cajun Seasoning, Olive Oil, Garlic, Lemon',
  instructions: '1. Rub chicken with seasoning. 2. Heat oil in pan. 3. Cook chicken until golden and fully cooked.',
  cooking_time: '30',
  servings: 4,
  difficulty: 'Medium'
)

Recipe.create(
  title: 'Pasta Carbonara',
  ingredients: 'Spaghetti, Eggs, Parmesan, Pancetta, Black Pepper',
  instructions: '1. Boil pasta. 2. Fry pancetta. 3. Mix eggs and cheese. 4. Toss with pasta and pancetta.',
  cooking_time: '20',
  servings: 4,
  difficulty: 'Medium'
)

Recipe.create(
  title: 'Chocolate Cake',
  ingredients: 'Flour, Sugar, Cocoa Powder, Eggs, Butter, Baking Powder',
  instructions: '1. Mix dry ingredients. 2. Add eggs and butter. 3. Bake in oven for 30 minutes.',
  cooking_time: '45',
  servings: 8,
  difficulty: 'Hard'
)

